/clusters/{clusterName}/scriptActions/{scriptName}",
        urlParameters: [
            subscriptionId,
            resourceGroupName,
     fm     clusterName,
            scriptName
        ],
        queryParameters: [
            apiVersion
        ],
        headerParameters: [
            acceptLanguage
        ],
        responses: {
            200: {},
            default: {
                bodyMapper: ErrorResponse
            }
        },
        serializer: serializer$5
    };
    var listByClusterOperationSpec$1 = {
        